"""Generate Pinterest upload and tracking CSVs from pinterest_campaign_v2.json."""
from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

CAMPAIGN_PATH = Path("data/marketing/pinterest_campaign_v2.json")
OUTPUT_DIR = Path("output/pinterest-v2/metadata")
README_PATH = OUTPUT_DIR / "README.md"


UPLOAD_FIELDS = [
    "pin_id",
    "file_name",
    "board_name",
    "pin_title",
    "pin_description",
    "destination_url",
    "alt_text",
    "keywords",
    "style",
    "property",
    "template",
    "status",
]

TRACKING_FIELDS = [
    "pin_id",
    "file_name",
    "board_name",
    "destination_url",
    "pinterest_url",
    "publish_date",
    "status",
    "impressions",
    "saves",
    "outbound_clicks",
    "landing_visits",
    "cta_clicks",
    "leads",
    "purchases",
    "ctr",
    "lead_rate",
    "purchase_rate",
    "notes",
]


def main() -> int:
    if not CAMPAIGN_PATH.exists():
        print(f"ERROR: campaign file not found: {CAMPAIGN_PATH}", file=sys.stderr)
        return 1

    data = json.loads(CAMPAIGN_PATH.read_text(encoding="utf-8"))
    pins = data.get("pins", [])

    if not pins:
        print("ERROR: no pins found in campaign file.", file=sys.stderr)
        return 1

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    upload_rows = []
    tracking_rows = []

    for pin in pins:
        keywords_str = " | ".join(pin.get("keywords", []))

        upload_rows.append({
            "pin_id": pin["id"],
            "file_name": pin["output_name"],
            "board_name": pin["board_name"],
            "pin_title": pin["pin_title"],
            "pin_description": pin["pin_description"],
            "destination_url": pin["destination_url"],
            "alt_text": pin["alt_text"],
            "keywords": keywords_str,
            "style": pin["style"],
            "property": pin["property"],
            "template": pin["template"],
            "status": "ready",
        })

        tracking_rows.append({
            "pin_id": pin["id"],
            "file_name": pin["output_name"],
            "board_name": pin["board_name"],
            "destination_url": pin["destination_url"],
            "pinterest_url": "",
            "publish_date": "",
            "status": "pending",
            "impressions": "",
            "saves": "",
            "outbound_clicks": "",
            "landing_visits": "",
            "cta_clicks": "",
            "leads": "",
            "purchases": "",
            "ctr": "",
            "lead_rate": "",
            "purchase_rate": "",
            "notes": "",
        })

    upload_path = OUTPUT_DIR / "pinterest_upload_sheet.csv"
    with open(upload_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=UPLOAD_FIELDS)
        writer.writeheader()
        writer.writerows(upload_rows)
    print(f"Upload sheet -> {upload_path} ({len(upload_rows)} rows)")

    tracking_path = OUTPUT_DIR / "pinterest_tracking_sheet.csv"
    with open(tracking_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=TRACKING_FIELDS)
        writer.writeheader()
        writer.writerows(tracking_rows)
    print(f"Tracking sheet -> {tracking_path} ({len(tracking_rows)} rows)")

    readme_content = """# Pinterest v2 — Metadata CSVs

## Files in this folder

- `pinterest_upload_sheet.csv` — Paste into Pinterest when uploading pins. One row per pin.
- `pinterest_tracking_sheet.csv` — Track performance metrics after publishing. One row per pin.
- `manifest.json` — Generated by render_pinterest_v2.py. Lists all PNG files with metadata.

## How to import to Google Sheets

1. Go to [Google Sheets](https://sheets.google.com) and create a new spreadsheet.
2. Click **File → Import**.
3. Upload `pinterest_upload_sheet.csv`.
4. Select **"Replace spreadsheet"** or **"Insert new sheet"**.
5. Click **Import data**.
6. Repeat for `pinterest_tracking_sheet.csv` in a second sheet tab.

## Upload sheet columns

| Column | Description |
|---|---|
| pin_id | Unique pin identifier (pin-001 through pin-032) |
| file_name | PNG filename to upload to Pinterest |
| board_name | Target Pinterest board |
| pin_title | Pin title (shown on Pinterest) |
| pin_description | Pin description — copy/paste into Pinterest upload form |
| destination_url | Destination URL with UTM tracking |
| alt_text | Accessibility alt text for the image |
| keywords | Relevant keywords separated by ` | ` |
| style | Visual style: Coastal, Minimalist, Sunset, Classic |
| property | Property name |
| template | Template used |
| status | `ready` = PNG generated, `pending` = not yet generated |

## Tracking sheet columns

After publishing, fill in these columns weekly:

| Column | Description |
|---|---|
| pinterest_url | Full URL of the published pin |
| publish_date | Date published (YYYY-MM-DD) |
| status | pending / live / paused / deleted |
| impressions | Views from Pinterest analytics |
| saves | Pin saves (repins) |
| outbound_clicks | Clicks from Pinterest to your site |
| landing_visits | Confirmed GA4 sessions from Pinterest |
| cta_clicks | Clicks on CTA buttons on landing page |
| leads | Email signups or Tally form starts |
| purchases | Stripe payments confirmed |
| ctr | outbound_clicks / impressions |
| lead_rate | leads / outbound_clicks |
| purchase_rate | purchases / outbound_clicks |
| notes | Notes on performance, creative, etc. |

## Winner criteria (after 7–10 days)

Declare a pin a winner if it shows:
- High outbound click rate (>1% CTR)
- High saves relative to impressions
- Confirmed leads or purchases from UTM tracking
- Clear visual clarity vs. lower-performing pins

---
*Generated by build_pinterest_metadata.py — MyGuest Pinterest v2*
"""

    README_PATH.write_text(readme_content, encoding="utf-8")
    print(f"README -> {README_PATH}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
