name: MyGuest Generator
on:
  repository_dispatch:
    types: [new-villa]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Generate Villa Page
        run: |
          python scripts/generate_villa.py '${{ github.event.client_payload.data }}'
      - name: Commit and Push
        run: |
          git config --global user.name "MyGuest Bot"
          git config --global user.email "bot@myguest.com"
          git add .
          git commit -m "New villa: ${{ github.event.client_payload.name }}"
          git push
